version: 2.1

orbs:
  node: circleci/node@7.2.1

jobs:
  verify:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - run: yarn install --immutable
      - attach_workspace:
          at: '.'
      - run: yarn test

  deploy-npm:
    docker:
      - image: cimg/openjdk:24.0-browsers
    steps:
      - checkout
      - node/install:
          node-version: '25.8.1'
      - attach_workspace:
          at: '.'
      - run: yarn install --immutable
      - run:
          command: |
            # From https://docs.npmjs.com/trusted-publishers#circleci-configuration
            NPM_ID_TOKEN=$(circleci run oidc get --claims '{"aud": "npm:registry.npmjs.org"}')
            export NPM_ID_TOKEN
            ./scripts/circle-publish-npm

workflows:
  verify_deploy:
    jobs:
      - verify:
          filters:
            tags:
              only: /.*/
      - deploy-npm:
          requires: [verify]
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
